name: OnkyoVolume

options:
  bundleIdPrefix: com.swack-tools
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true

settings:
  MARKETING_VERSION: 1.0.13
  CURRENT_PROJECT_VERSION: 1

targets:
  OnkyoVolume:
    type: application
    platform: macOS
    sources:
      - OnkyoVolume
      - OnkyoVolume/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.swack-tools.onkyo-volume
        INFOPLIST_FILE: OnkyoVolume/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_VERSION: "5.9"
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "Apple Development"
          DEVELOPMENT_TEAM: LBW5YC4F5G
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "Developer ID Application: SWACKTECH, LLC (WHS8S6ZW43)"
          DEVELOPMENT_TEAM: WHS8S6ZW43
          ENABLE_HARDENED_RUNTIME: YES
          CODE_SIGN_ENTITLEMENTS: OnkyoVolume/OnkyoVolume.entitlements
          OTHER_CODE_SIGN_FLAGS: --timestamp
    info:
      path: OnkyoVolume/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSUIElement: true
        NSHumanReadableCopyright: ""
        NSPrincipalClass: NSApplication

  OnkyoVolumeTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - OnkyoVolumeTests
      - path: OnkyoVolume/OnkyoClient-simple.swift
    dependencies:
      - target: OnkyoVolume
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.swack-tools.onkyo-volume-tests
      MACOSX_DEPLOYMENT_TARGET: "13.0"
      SWIFT_VERSION: "5.9"
      GENERATE_INFOPLIST_FILE: YES
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/OnkyoVolume.app/Contents/MacOS/OnkyoVolume
      BUNDLE_LOADER: $(TEST_HOST)
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: "-"

schemes:
  OnkyoVolume:
    build:
      targets:
        OnkyoVolume: all
        OnkyoVolumeTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - OnkyoVolumeTests
